name: github action using self-hosted runner i.e EC2 insatnces

on: [push]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-versions: [16, 17]

    steps:
      - name: checkout repo
        use: actions/checkout@v3

      - name: set up node.js
        use: actions/setup-node@v3
        with:
          node-versions: ${{matrix.node-versions}}

      - name: install dependences
        use: npm instal

      - name: build project
        use: npm run build
